[package]
name = "heka"
edition.workspace = true
version.workspace = true
authors.workspace = true
description = "eka ui computing library"

[dependencies]
ansi_term = { workspace = true, optional = true}


[features]
default = []
debug = ["ansi_term"]
